apt update && \
apt install -y -qq \
build-essential \
cmake \
cmake-curses-gui \
freeglut3-dev \
curl \
emacs-nox \
ca-certificates \
git \
gfortran \
libace-dev \
libboost-filesystem-dev \
libboost-system-dev \
libboost-thread-dev \
libdc1394-22-dev \
libedit-dev \
libeigen3-dev \
libgsl0-dev \
libjpeg-dev \
liblua5.1-dev \
libode-dev \
libopencv-dev \
libsdl1.2-dev \
libtinyxml-dev \
libv4l-dev \
libxml2-dev \
lua5.1 \
portaudio19-dev \
qml-module-qt-labs-folderlistmodel \
qml-module-qt-labs-settings \
qml-module-qtmultimedia \
qml-module-qtquick-controls \
qml-module-qtquick-dialogs \
qml-module-qtquick-window2 \
qml-module-qtquick2 \
qtbase5-dev \
qtdeclarative5-dev \
qtmultimedia5-dev \
swig \
libmatio-dev \
libirrlicht-dev \
libspdlog-dev \
libblas-dev \
liblapack-dev \
patch \
libmetis-dev \
nlohmann-json3-dev \
glmark2 \
gnupg2 \
htop \
iputils-ping \
lsb-release \
mesa-utils \
nano \
psmisc \
sudo \
unzip \
vim \
wget \
libqt5opengl5-dev \
tmuxinator \
ninja-build
